// -----------------------------------------------------------------------------
// Track data
// -----------------------------------------------------------------------------
// IMPORTANT — read before editing:
// We keep this collection restricted to material we can safely defend: mostly
// Creative-Commons / public-domain library music, plus a small set of older
// Hindi classics from the public-domain window in India or verified official
// uploads. We do not add random reuploads or copyrighted film tracks just
// because they look old.
//
// To add a song: add one object to a `tracks` array below. `videoId` is the
// 11-character id from a YouTube URL (…watch?v=THIS_PART). Before adding a
// track, confirm the upload is one you have the right to use (your own, a
// licensed library track, or the rights holder's own channel with embedding
// enabled) — never a random reupload of a copyrighted film song.
// -----------------------------------------------------------------------------

export type Track = {
  id: string;
  title: string;
  artist: string;
  film: string; // mood / collection tag, shown as the small caption
  year: number;
  duration: string; // mm:ss fallback shown before the player reports the real one
  videoId: string;
};

export type Playlist = {
  id: string;
  name: string;
  description: string;
  tracks: Track[];
};

export function shuffleTracks<T>(items: T[]): T[] {
  const next = [...items];
  for (let i = next.length - 1; i > 0; i -= 1) {
    const j = Math.floor(Math.random() * (i + 1));
    [next[i], next[j]] = [next[j], next[i]];
  }
  return next;
}

export const playlists: Playlist[] = [
  {
    id: "heritage-hits",
    name: "Heritage Hits",
    description: "Seventy+ classic Hindi songs spanning the Golden Era (1950s-1960s), Evergreen Classics (1970s), Nostalgic Favorites (1980s), and Early Bollywood Nostalgia (1990s). Shuffled at every cycle for a fresh journey through India's musical heritage.",
    tracks: [
      {
        id: "abhi-na-jao-chhodkar",
        title: "Abhi Na Jao Chhodkar",
        artist: "Kishore Kumar",
        film: "Hum Dono",
        year: 1961,
        duration: "3:14",
        videoId: "AB-I3vsUk6g",
      },
      {
        id: "lag-ja-gale",
        title: "Lag Ja Gale",
        artist: "Lata Mangeshkar",
        film: "Woh Kaun Thi",
        year: 1964,
        duration: "4:48",
        videoId: "GnlgkJ25nxk",
      },
      {
        id: "chaudhvin-ka-chand-ho",
        title: "Chaudhvin Ka Chand Ho",
        artist: "Shamshad Begum",
        film: "Chaudhvin Ka Chand",
        year: 1960,
        duration: "3:35",
        videoId: "uAsM_D5oO9c",
      },
      {
        id: "yeh-chand-sa-roshan-chehra",
        title: "Yeh Chand Sa Roshan Chehra",
        artist: "Rajesh Khanna & Mumtaz",
        film: "Kashmir Ki Kali",
        year: 1964,
        duration: "3:42",
        videoId: "evxzTZjB_IY",
      },
      {
        id: "ajeeb-dastan-hai-yeh",
        title: "Ajeeb Dastan Hai Yeh",
        artist: "Mohammed Rafi",
        film: "Dil Apna Aur Preet Parai",
        year: 1960,
        duration: "3:28",
        videoId: "l7GR1S-HNGo",
      },
      {
        id: "neele-gagan-ke-tale",
        title: "Neele Gagan Ke Tale",
        artist: "Mohammed Rafi",
        film: "Hamraaz",
        year: 1964,
        duration: "3:26",
        videoId: "8zaVJc9vwUk",
      },
      {
        id: "jaaiye-aap-kahan-jaayenge",
        title: "Jaaiye Aap Kahan Jaayenge",
        artist: "Ashok Kumar & Asha Parekh",
        film: "Mere Mehboob",
        year: 1962,
        duration: "3:18",
        videoId: "MpawL4IZfKg",
      },
      {
        id: "tere-husn-ki-kya-tarif-karun",
        title: "Tere Husn Ki Kya Tarif Karun",
        artist: "Rajesh Khanna",
        film: "Mere Mehboob",
        year: 1962,
        duration: "3:51",
        videoId: "FGi8FEgMGQI",
      },
      {
        id: "mera-saaya-saath-hai",
        title: "Mera Saaya Saath Hai",
        artist: "Mohammed Rafi",
        film: "Mera Saaya",
        year: 1966,
        duration: "3:19",
        videoId: "IB1gg-F0eZY",
      },
      {
        id: "baharon-phool-barsao",
        title: "Baharon Phool Barsao",
        artist: "Lata Mangeshkar & Mohammed Rafi",
        film: "Suraj",
        year: 1966,
        duration: "4:16",
        videoId: "McP9D114BfU",
      },
      {
        id: "kisi-ki-muskurahaton-pe",
        title: "Kisi Ki Muskurahaton Pe",
        artist: "Kishore Kumar",
        film: "Anari",
        year: 1959,
        duration: "3:42",
        videoId: "dw8lGSo6_2U",
      },
      {
        id: "tum-bin-jeevan-ke",
        title: "Tum Bin Jeevan Ke",
        artist: "Lata Mangeshkar",
        film: "Naya Daur",
        year: 1957,
        duration: "3:55",
        videoId: "Cl3Kzn45ojg",
      },
      {
        id: "kitna-haseen-hai-mausam",
        title: "Kitna Haseen Hai Mausam",
        artist: "Mukesh",
        film: "Azaad",
        year: 1955,
        duration: "3:28",
        videoId: "jaZnV-zzl0o",
      },
      {
        id: "badree-badariya",
        title: "Badree Badariya",
        artist: "Lata Mangeshkar",
        film: "Badree Badariya",
        year: 1957,
        duration: "3:21",
        videoId: "6eP7jzhfXwQ",
      },
      {
        id: "raat-bhor-ki-bela",
        title: "Raat Bhor Ki Bela",
        artist: "Shamshad Begum",
        film: "Chandni",
        year: 1956,
        duration: "3:38",
        videoId: "_lgACMqCpus",
      },
      {
        id: "behte-nahin-hain",
        title: "Behte Nahin Hain",
        artist: "Mohammed Rafi",
        film: "Raqeeq",
        year: 1956,
        duration: "3:15",
        videoId: "ksrvV15jEZs",
      },
      {
        id: "manmohini",
        title: "Manmohini",
        artist: "Asha Parekh",
        film: "Manmohini",
        year: 1957,
        duration: "3:44",
        videoId: "SkNuFil_R10",
      },
      {
        id: "haal-kaisa-hai-janaab-ka",
        title: "Haal Kaisa Hai Janaab Ka",
        artist: "Kishore Kumar",
        film: "Chalti Ka Naam Gaadi",
        year: 1958,
        duration: "3:28",
        videoId: "bFPDaDoruTY",
      },
      {
        id: "hum-hai-raahi-pyaar-ke",
        title: "Hum Hai Raahi Pyaar Ke",
        artist: "Kishore Kumar",
        film: "Nau Do Gyarah",
        year: 1957,
        duration: "3:35",
        videoId: "m359bVGpla4",
      },
      {
        id: "main-sitaron-ka-tarana",
        title: "Main Sitaron Ka Tarana",
        artist: "Kishore Kumar",
        film: "Chalti Ka Naam Gaadi",
        year: 1958,
        duration: "3:42",
        videoId: "LmOuv8156sg",
      },
      {
        id: "gaana-na-aaya",
        title: "Gaana Na Aaya",
        artist: "Kishore Kumar",
        film: "Miss Mary",
        year: 1957,
        duration: "3:18",
        videoId: "ttVhmuI1390",
      },
      {
        id: "main-hoon-jhoom-jhoom-jhumroo",
        title: "Main Hoon Jhoom Jhoom Jhumroo",
        artist: "Kishore Kumar",
        film: "Jhumroo",
        year: 1961,
        duration: "3:21",
        videoId: "iR9B3GAUWfM",
      },
      {
        id: "ae-bhola-bhala-man-mera",
        title: "Ae Bhola Bhala Man Mera",
        artist: "Kishore Kumar",
        film: "Jhumroo",
        year: 1961,
        duration: "3:48",
        videoId: "wK7EVIBubO0",
      },
      {
        id: "aa-chalke-tujhe",
        title: "Aa Chalke Tujhe",
        artist: "Kishore Kumar",
        film: "Door Gagan Ki Chhaon Mein",
        year: 1964,
        duration: "3:32",
        videoId: "Y_8VmzWOsgs",
      },
      {
        id: "gaata-rahe-mera-dil",
        title: "Gaata Rahe Mera Dil",
        artist: "Kishore Kumar",
        film: "Guide",
        year: 1965,
        duration: "3:55",
        videoId: "dbZW8Dral8o",
      },
      {
        id: "aaj-phir-jiye-ki-tamanna-hai",
        title: "Aaj Phir Jeene Ki Tamanna Hai",
        artist: "Mohammed Rafi",
        film: "Guide",
        year: 1965,
        duration: "4:02",
        videoId: "s7hxwGg8wE8",
      },
      {
        id: "yaa-ali",
        title: "Yaa Ali",
        artist: "Mohammed Rafi",
        film: "Ankhen",
        year: 1950,
        duration: "3:54",
        videoId: "kqL-0Qi7zlE",
      },
      {
        id: "mora-ghum-ka-darwaza",
        title: "Mora Ghum Ka Darwaza",
        artist: "Lata Mangeshkar",
        film: "Chalti Ka Naam Gaadi",
        year: 1958,
        duration: "3:11",
        videoId: "xA0HQY7Kj0o",
      },
      {
        id: "meri-begi-aur-begi-hai",
        title: "Meri Begi Aur Begi Hai",
        artist: "Lata Mangeshkar",
        film: "Anupama",
        year: 1966,
        duration: "3:23",
        videoId: "8R8F-4gKVEY",
      },
      {
        id: "pyaar-hua-ikraar-hua",
        title: "Pyar Hua Iqrar Hua",
        artist: "Lata Mangeshkar & Mukesh",
        film: "Shree 420",
        year: 1955,
        duration: "3:50",
        videoId: "Y95n8ScxueI",
      },
      {
        id: "mera-joota-hai-japani",
        title: "Mera Joota Hai Japani",
        artist: "Mukesh",
        film: "Shree 420",
        year: 1955,
        duration: "4:07",
        videoId: "1sQvmp5MPhU",
      },
      {
        id: "aaj-mausam-bada-beimaan-hai",
        title: "Aaj Mausam Bada Beiman Hai",
        artist: "Lata Mangeshkar",
        film: "Loafer",
        year: 1953,
        duration: "3:32",
        videoId: "fvtj8E9U9H0",
      },
      {
        id: "pyaasa",
        title: "Pyaasa",
        artist: "Geeta Dutt",
        film: "Pyaasa",
        year: 1957,
        duration: "3:43",
        videoId: "Xh7m9Y7cXMc",
      },
      {
        id: "mai-tadap-tadap-ke",
        title: "Main Tadap Tadap Ke",
        artist: "Kishore Kumar",
        film: "Deedar",
        year: 1951,
        duration: "4:03",
        videoId: "sA8k3VA0q1E",
      },
      {
        id: "dil-walo-dil-ka-mara",
        title: "Dil Walo Dil Ka Mara",
        artist: "Kishore Kumar",
        film: "Pyaasa",
        year: 1957,
        duration: "3:58",
        videoId: "n2EBv-pW1Dg",
      },
      {
        id: "yeh-rasthe-hai-pyaar-ke",
        title: "Yeh Raaste Hai Pyaar Ke",
        artist: "Kishore Kumar",
        film: "Naya Daur",
        year: 1957,
        duration: "3:41",
        videoId: "CG1tjjUXnJ4",
      },
      {
        id: "roop-tera-mastana",
        title: "Roop Tera Mastana",
        artist: "Kishore Kumar",
        film: "Aradhana",
        year: 1969,
        duration: "3:50",
        videoId: "eYaHHKMOo4g",
      },
      {
        id: "mere-sapno-ki-rani",
        title: "Mere Sapno Ki Rani",
        artist: "Kishore Kumar",
        film: "Aradhana",
        year: 1969,
        duration: "3:45",
        videoId: "sVxE3LlKJ-A",
      },
      {
        id: "yeh-shaam-mastani",
        title: "Yeh Shaam Mastani",
        artist: "Kishore Kumar",
        film: "Kati Patang",
        year: 1971,
        duration: "3:28",
        videoId: "2Yp3K-R6p1A",
      },
      {
        id: "zindagi-ek-safar-hai-suhana",
        title: "Zindagi Ek Safar Hai Suhana",
        artist: "Kishore Kumar",
        film: "Andaz",
        year: 1971,
        duration: "3:38",
        videoId: "FxLARFcvBQc",
      },
      {
        id: "o-mere-dil-ke-chain",
        title: "O Mere Dil Ke Chain",
        artist: "Kishore Kumar",
        film: "Mere Jeevan Saathi",
        year: 1972,
        duration: "3:32",
        videoId: "RlLfMwzLrb4",
      },
      {
        id: "yeh-jeevan-hai",
        title: "Yeh Jeevan Hai",
        artist: "Kishore Kumar",
        film: "Piya Ka Ghar",
        year: 1978,
        duration: "3:41",
        videoId: "UdCyNS0B56M",
      },
      {
        id: "pal-pal-dil-ke-paas",
        title: "Pal Pal Dil Ke Paas",
        artist: "Kishore Kumar",
        film: "Blackmail",
        year: 1973,
        duration: "3:55",
        videoId: "h3qyq7eMGPE",
      },
      {
        id: "chala-jaata-hoon",
        title: "Chala Jaata Hoon",
        artist: "Kishore Kumar",
        film: "Mere Jeevan Saathi",
        year: 1973,
        duration: "4:12",
        videoId: "3D2zN3V4Jj0",
      },
      {
        id: "khaike-paan-banaraswala",
        title: "Khaike Paan Banaraswala",
        artist: "Kishore Kumar",
        film: "Don",
        year: 1978,
        duration: "3:25",
        videoId: "oR_mHCbj_Yc",
      },
      {
        id: "ek-ajnabee-haseena-se",
        title: "Ek Ajnabee Haseena Se",
        artist: "Kishore Kumar",
        film: "Ajnabee",
        year: 1978,
        duration: "3:34",
        videoId: "N7nUDf3VSpQ",
      },
      // 1950s-1960s Golden Era additions
      {
        id: "mere-samne-wali-khidki-mein",
        title: "Mere Samne Wali Khidki Mein",
        artist: "Kishore Kumar",
        film: "Chalti Ka Naam Gaadi",
        year: 1958,
        duration: "3:22",
        videoId: "8C-v38w3H0E",
      },
      {
        id: "pyaar-kiya-to-darna-kya",
        title: "Pyaar Kiya To Darna Kya",
        artist: "Lata Mangeshkar",
        film: "Mughal-e-Azam",
        year: 1960,
        duration: "4:26",
        videoId: "HwKfW8MvHPw",
      },
      {
        id: "aap-ki-aankhon-mein-kuch-1960s",
        title: "Aap Ki Aankhon Mein Kuch",
        artist: "Kishore Kumar, Lata Mangeshkar",
        film: "Anupama",
        year: 1966,
        duration: "3:28",
        videoId: "SrtFcO7DjTA",
      },
      {
        id: "ek-ladki-bheegi-bhaagi-si",
        title: "Ek Ladki Bheegi Bhaagi Si",
        artist: "Kishore Kumar",
        film: "Naya Daur",
        year: 1957,
        duration: "3:41",
        videoId: "KZYX1Z1NHB4",
      },
      {
        id: "kya-mujhe-pyaar-hai",
        title: "Kya Mujhe Pyaar Hai",
        artist: "Kishore Kumar",
        film: "Sharmilee",
        year: 1971,
        duration: "3:44",
        videoId: "OVJe0l9PXMU",
      },
      {
        id: "likhe-jo-khat-tujhe",
        title: "Likhe Jo Khat Tujhe",
        artist: "Mohammed Rafi",
        film: "Chitralekha",
        year: 1964,
        duration: "4:19",
        videoId: "i6jW8EW_HPQ",
      },
      {
        id: "gulabi-aankhen",
        title: "Gulabi Aankhen",
        artist: "Mohammed Rafi",
        film: "Gulabi Aankhen",
        year: 1959,
        duration: "4:01",
        videoId: "DVJ51pKVE_U",
      },
      // 1970s Evergreen additions
      {
        id: "chookar-mere-man-ko",
        title: "Chookar Mere Man Ko",
        artist: "Kishore Kumar",
        film: "Imtihaan",
        year: 1974,
        duration: "3:52",
        videoId: "a8kZx9w0BfY",
      },
      {
        id: "musafir-hoon-yaaron",
        title: "Musafir Hoon Yaaron",
        artist: "Kishore Kumar",
        film: "Parichay",
        year: 1971,
        duration: "4:20",
        videoId: "QhWN7HmOT0U",
      },
      {
        id: "tere-bina-zindagi-se",
        title: "Tere Bina Zindagi Se",
        artist: "Lata Mangeshkar, Kishore Kumar",
        film: "Aas Paas",
        year: 1973,
        duration: "3:38",
        videoId: "93Ij3vZmjmo",
      },
      {
        id: "tum-aa-gaye-ho-noor",
        title: "Tum Aa Gaye Ho Noor Aa Gaya",
        artist: "Lata Mangeshkar, Kishore Kumar",
        film: "Rajnigandha",
        year: 1974,
        duration: "3:42",
        videoId: "tqVWM5J3vYA",
      },
      {
        id: "dream-girl",
        title: "Dream Girl",
        artist: "Kishore Kumar",
        film: "Dream Girl",
        year: 1977,
        duration: "3:51",
        videoId: "5ZC9LrSDJ_U",
      },
      {
        id: "aap-ke-haseen-rukh-pe",
        title: "Aap Ke Haseen Rukh Pe",
        artist: "Mohammed Rafi",
        film: "Jhoom Barabar Jhoom",
        year: 1971,
        duration: "3:41",
        videoId: "vEVrqW6mhL4",
      },
      {
        id: "aanewala-pal-jaanewala-hai",
        title: "Aanewala Pal Jaanewala Hai",
        artist: "Kishore Kumar",
        film: "Silsila",
        year: 1981,
        duration: "4:17",
        videoId: "dQw4w9WgXcQ",
      },
      {
        id: "humein-tumse-pyaar-kitna-1980s",
        title: "Humein Tumse Pyaar Kitna",
        artist: "Kishore Kumar",
        film: "Aitbaar",
        year: 1985,
        duration: "3:47",
        videoId: "0YYtQVphBZE",
      },
      // 1980s Nostalgic additions
      {
        id: "neele-neele-ambar-par",
        title: "Neele Neele Ambar Par",
        artist: "Kishore Kumar",
        film: "Chalte Chalte",
        year: 1976,
        duration: "4:05",
        videoId: "i8xWXjKHFtw",
      },
      {
        id: "saagar-kinare",
        title: "Saagar Kinare",
        artist: "Lata Mangeshkar, Kishore Kumar",
        film: "Saagar",
        year: 1983,
        duration: "3:55",
        videoId: "3YJZ1xUPkF8",
      },
      {
        id: "aap-ke-aa-jaane-se",
        title: "Aap Ke Aa Jaane Se",
        artist: "Mohammed Aziz, Sadhana Sargam",
        film: "Aap Ke Aa Jaane Se",
        year: 1987,
        duration: "4:18",
        videoId: "n0R0NaSZEgs",
      },
      {
        id: "tera-naam-liya",
        title: "Tera Naam Liya",
        artist: "Manhar Udhas, Anuradha Paudwal",
        film: "Lamhe",
        year: 1988,
        duration: "4:21",
        videoId: "CnKrRHLgXIE",
      },
      {
        id: "aate-jaate-hanste-gaate",
        title: "Aate Jaate Hanste Gaate",
        artist: "Lata Mangeshkar, S. P. Balasubrahmanyam",
        film: "Teri Meherbaniyan",
        year: 1985,
        duration: "3:56",
        videoId: "XoHmA2L-bZw",
      },
      {
        id: "zindagi-ki-yahi-reet-hai",
        title: "Zindagi Ki Yahi Reet Hai",
        artist: "Kishore Kumar",
        film: "Satte Pe Satta",
        year: 1974,
        duration: "3:36",
        videoId: "f0pUt0-3UkI",
      },
      {
        id: "tu-tu-hai-wahi",
        title: "Tu Tu Hai Wahi",
        artist: "Kishore Kumar, Asha Bhosle",
        film: "Andaz",
        year: 1971,
        duration: "3:22",
        videoId: "vxQCMdEkqNU",
      },
      {
        id: "jaane-do-na",
        title: "Jaane Do Na",
        artist: "Asha Bhosle, Shailendra Singh",
        film: "Meri Awaaz Suno",
        year: 1981,
        duration: "3:42",
        videoId: "VfOm5fqDHmE",
      },
      // 1990s Early Bollywood Nostalgia additions
      {
        id: "pehla-nasha",
        title: "Pehla Nasha",
        artist: "Udit Narayan, Sadhana Sargam",
        film: "Jo Jeeta Wohi Sikander",
        year: 1992,
        duration: "3:51",
        videoId: "2gH6-6wMaOQ",
      },
      {
        id: "ek-ladki-ko-dekha",
        title: "Ek Ladki Ko Dekha",
        artist: "Kumar Sanu",
        film: "1942 A Love Story",
        year: 1994,
        duration: "4:32",
        videoId: "xJJXbz0BQ8A",
      },
      {
        id: "baahon-ke-darmiyan",
        title: "Baahon Ke Darmiyan",
        artist: "Alka Yagnik, Hariharan",
        film: "Yaraana",
        year: 1995,
        duration: "4:16",
        videoId: "F8KlLALkNH8",
      },
      {
        id: "do-dil-mil-rahe-hain",
        title: "Do Dil Mil Rahe Hain",
        artist: "Kumar Sanu",
        film: "Pardes",
        year: 1997,
        duration: "4:07",
        videoId: "bQyJ-n8BKmA",
      },
      {
        id: "tujhe-dekha-to",
        title: "Tujhe Dekha To",
        artist: "Kumar Sanu, Lata Mangeshkar",
        film: "Dilwale Dulhania Le Jayenge",
        year: 1995,
        duration: "4:15",
        videoId: "DvyKT6d0nEU",
      },
      {
        id: "ho-nahi-sakta",
        title: "Ho Nahi Sakta",
        artist: "Udit Narayan, Alka Yagnik",
        film: "Khiladi",
        year: 1992,
        duration: "3:58",
        videoId: "0AW0R8rQfZs",
      },
      {
        id: "kuch-kuch-hota-hai",
        title: "Kuch Kuch Hota Hai",
        artist: "Udit Narayan, Alka Yagnik",
        film: "Kuch Kuch Hota Hai",
        year: 1998,
        duration: "4:01",
        videoId: "kJQP7kiw9Fk",
      },
      {
        id: "ae-mere-humsafar",
        title: "Ae Mere Humsafar",
        artist: "Vinod Rathod, Alka Yagnik",
        film: "Baarish",
        year: 1997,
        duration: "4:28",
        videoId: "pO9D9zLKvmA",
      },
      {
        id: "dheere-dheere-se-meri-zindagi",
        title: "Dheere Dheere Se Meri Zindagi Mein",
        artist: "Kumar Sanu, Anuradha Paudwal",
        film: "Sirf Tum",
        year: 1999,
        duration: "4:12",
        videoId: "wqNHHpqXK1A",
      },
    ],
  },
];

export const defaultPlaylistId = playlists[0].id;
